service: gpsgend

logger:
  format: text # json
  level: info # info, warn, debug, error

api:
  http:
    addr: 0.0.0.0:32300

storage:    
  mongodb:
    uri: mongodb://root:root@localhost:27017
    collectionName: devices  
    databaseName: gpsgend